name: Pipeline de CI/CD - Meu Primeiro Robô

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verificacoes-basicas:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar código
        uses: actions/checkout@v3

      - name: 2. Verificar estrutura
        run: ls -la

      - name: 3. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 4. Executar aplicação
        run: node app.js

      - name: 5. Mensagem sucesso
        run: echo "O Pipeline rodou perfeitamente e o app está funcionando!"
